# Server configuration
server_config = {
  hostname: "trofidalS",
  ip: "192.168.56.110",
  memory: 4096,
  cpu: 1
}

server_script = <<-SHELL
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC="server --bind-address=#{server_config[:ip]} --flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh -
    echo "Waiting for k3s to be ready..."
    until kubectl get nodes >/dev/null 2>&1; do
        sleep 1
        echo "Waiting for K3s..."
    done

    echo "K3s is ready!"
    cp /var/lib/rancher/k3s/server/token /vagrant
    cp /var/lib/rancher/k3s/server/node-token /vagrant
    cp /etc/rancher/k3s/k3s.yaml /vagrant
    echo "Server token copied."
    echo "Node Server token copied."
    echo "alias k='kubectl'" >> /home/vagrant/.bashrc
    source /home/vagrant/.bashrc
    echo "Kubectl alias set"
    echo "Setting broadcast address for eth1..."
    sudo ip addr flush dev eth1
    sudo ip addr add 192.168.56.110/24 broadcast 192.168.56.255 dev eth1
    sudo ip link set eth1 up
    echo "Broadcast address set to 192.168.56.255"
    echo "K3s Server Ready" 
    SHELL

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "generic/alpine312"

  config.vm.define server_config[:hostname], primary: true do |controller|
    controller.vm.network "private_network", ip: server_config[:ip]
    controller.vm.synced_folder "./config", "/vagrant", type:"virtualbox"
    controller.vm.hostname = server_config[:hostname]
    controller.vm.provider "virtualbox" do |hv|
      hv.memory = server_config[:memory]
      hv.cpus = server_config[:cpu]
      hv.name = server_config[:hostname]
    end
    controller.vm.provision "shell", inline: server_script
  end
end